name: Despliegue Front QA

on:
  push:
    branches: [ "develop" ] # Se activa solo en rama main
  workflow_dispatch:

env:
  PROJECT_ID: 'restomap-478918'
  REGION: 'us-central1'
  REPO_NAME: 'repo'
  SERVICE_NAME: 'frontend-prod' # Nombre distintivo para producción
  BACKEND_SERVICE_NAME: 'backend-prod' # Debe coincidir con el nombre del back de arriba

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/414435283954/locations/global/workloadIdentityPools/github-pool/providers/github-provider1'
          service_account: 'github-deploy-sa@restomap-478918.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build y Push Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
          echo "Buscando URL del servicio backend: ${{ env.BACKEND_SERVICE_NAME }}"
          
          # Intentamos obtener la URL de PROD. Si falla, usamos un placeholder para no romper el build.
          if ! BACKEND_URL=$(gcloud run services describe ${{ env.BACKEND_SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)' 2>/dev/null); then
            echo "⚠️ ADVERTENCIA: No se encontró el servicio Backend PROD."
            BACKEND_URL="https://api-prod-pendiente.run.app"
          fi
          
          echo "URL Backend Prod encontrada: $BACKEND_URL"
          
          IMAGE_TAG="us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend-prod:${{ github.sha }}"
          
          # Crear carpeta public por seguridad (como hicimos en QA)
          mkdir -p public
          
          # Construcción
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=$BACKEND_URL \
            -t $IMAGE_TAG .
            
          docker push $IMAGE_TAG
          
          # Despliegue (con min-instances 1 para mejor rendimiento en prod)
          gcloud run deploy ${{ env.SERVICE_NAME }} --image $IMAGE_TAG --region ${{ env.REGION }} --allow-unauthenticated --min-instances 1